// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App — Wails 绑定的 Go 结构体
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

/**
 * @param {string} source
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function ClearCache(source) {
    return $Call.ByID(1413834504, source).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetAllConfig() {
    return $Call.ByID(1520985876).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutoStart() {
    return $Call.ByID(398025584);
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetCacheInfo() {
    return $Call.ByID(1735807799).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetConfig() {
    return $Call.ByID(1200034045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} mode
 * @returns {$CancellablePromise<string>}
 */
export function GetEnvVars(mode) {
    return $Call.ByID(363814436, mode);
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetLogs(limit) {
    return $Call.ByID(1743981476, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetProxyStatus() {
    return $Call.ByID(1800065723);
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetProxySwitchStatus() {
    return $Call.ByID(719178511).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetStats() {
    return $Call.ByID(2859423874).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetSystemStatus() {
    return $Call.ByID(1366046352).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsAdmin() {
    return $Call.ByID(4064921852);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function RestartProxy() {
    return $Call.ByID(1240580212);
}

/**
 * @param {{ [_ in string]?: any }} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(3442292638, cfg);
}

/**
 * @param {{ [_ in string]?: any }} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfigViaAdmin(cfg) {
    return $Call.ByID(1146097381, cfg);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(2987688963);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function StartProxy() {
    return $Call.ByID(2835838209);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Startup() {
    return $Call.ByID(2154875234);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function StopProxy() {
    return $Call.ByID(3345047379);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function ToggleAutoStart(enabled) {
    return $Call.ByID(1830522718, enabled);
}

/**
 * @param {string} which
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function ToggleProxySwitch(which, enabled) {
    return $Call.ByID(3965885971, which, enabled);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
